### ISSUE TITLE
Failed Pre-Requisite Check but Node.js and Topojson already installed Windows 10

### ISSUE THREAD

**Issue by diegojpadron** [sbenten/d3MapRenderer#11]
2015-09-27T23:43:10 0   model 2.10.1-Pisa
2015-09-27T23:43:10 0   model 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
2015-09-27T23:43:10 0   topo Windows
2015-09-27T23:43:10 2   model Exception
            Traceback (most recent call last):
              File "C:/Users/nefertiti/.qgis2/python/plugins\d3MapRenderer\logic.py", line 100, in hasTopoJson
                found = self.topojson.helper.hasTopojson()
              File "C:/Users/nefertiti/.qgis2/python/plugins\d3MapRenderer\osHelp.py", line 139, in hasTopojson
                nodeFound = self.getNodeJsPath()
              File "C:/Users/nefertiti/.qgis2/python/plugins\d3MapRenderer\osHelp.py", line 235, in getNodeJsPath
                except self.reg.WindowsError as e:
            AttributeError: 'module' object has no attribute 'WindowsError'

**Comment by sbenten** [comment]
Checked on Windows 7, 8.1 and 10 OK.
The actual error is being masked by built in WindowsError exception
being fetched from the _winreg module. This is now fixed, but the
underlying problem remains.
Please check the registry setting for
HKEY_CURRENT_USER\Software\node.js\InstallPath exists and that no
restrictions on the computer prevent access to the registry.

**Comment by tomchadwin** [comment]
What should `HKEY_CURRENT_USER\Software\node.js\InstallPath` be set to?

**Comment by seabamirum** [comment]
I just added a blank value and it worked for me.

**Comment by sbenten** [comment]
Yes, that will get it past the prerequisite check.

However, the check is there for a reason, the code will just error later on
when you run the output process, as it can't call the Node executable and
the topojson npm package. On Windows this information is stored in two
registry keys:

**HKEY_CURRENT_USER\Software\Node.js\InstallPath**  which is the path to the
Node.js installation folder, and should have a value along the lines
of **C:\Program Files\nodejs\**

**HKEY_CURRENT_USER\Environment\PATH**  which is where your Environment
variables are stored, and should have the path to the NPM packages
(possibly along with a few other things separated by a semicolon)
**C:\Users\Simon\AppData\Roaming\npm**;C:\Program Files\QGIS
Wien\bin;C:\Program Files\QGIS Wien\apps\qgis\bin

The Node.js installer should be setting these values for you, and Node.js
itself may require other registry keys. However, that is all the
information the plugin requires to create a long command string along the
lines of:

**C:\Program Files\nodejs\**node.exe
**C:\Users\Simon\AppData\Roaming\npm**\node_modules\topojson\bin\topojson
-o C:\Users\Simon\Documents\EnglishIMD\topo\LSOA2001IMD.json --id-property
LSOA01CD -p d3Css -s 1e-9 --
l1=C:\Users\Simon\Documents\EnglishIMD\shp\LSOA_2001_IMD.shp

I'm going to add a GeoJson export as soon as my contracts come to an end
(d3 doesn't require TopoJson, I just went down that particular route as it
produces smaller files) and I'll add an internal conversion to TopoJson at
a later date.
