### ISSUE TITLE
Any progress on d3MapRenderer?

### ISSUE THREAD

**Issue by tomchadwin** [sbenten/d3MapRenderer#12]
It would be great to explore incorporating d3 output in qgis2web.

**Comment by sbenten** [comment]
Unfortunately not, I've been swamped with other things. To remove the
dependency on node.js requires a large chunk of work which slowed any other
developments.

However, you don't have to use topojson,  the geojson output from qgis2web
will work fine and there should be plenty of examples on the web. If you're
going to integrate a d3 viz with leaflet there are a few examples I've
stumbled on which should be easily found and would be fantastic in your
plugin.

Active development of D3MapRenderer will resume in the new year.

**Comment by tomchadwin** [comment]
So why do you use topojson, or of interest?

**Comment by sbenten** [comment]
It's a more compact dataset, so can handle more complicated topology
without leading to stupidly large file sizes.
As described by Mr Bostock: https://github.com/mbostock/topojson
The datasets I was working no with were up to 5mb in topojson, but over
100mb in geojson.
I was  thinking of adding geojson support to d3MapRenderer but only as a
stop gap to the installation issues.

**Comment by tomchadwin** [comment]
I'll look into d3 with GeoJson. Not trying to produce composite d3 plus Leaflet. Interested in pure d3 maps.

**Comment by tomchadwin** [comment]
To remove the node.js dependency, can you use this:

https://github.com/calvinmetcalf/topojson.py

**Comment by sbenten** [comment]
Thanks, though I think I unsuccessfully tried to use this several months
ago. I'll take another look...

**Comment by sbenten** [comment]
Added the ability to export to GeoJson on the master branch, if you want to take a look.
I'll get back to adding a python based topojson conversion after adding a few more bits of functionality to the plugin.
I'll close this issue for now.
