### ISSUE TITLE
Display of output fails with no webserver

### ISSUE THREAD

**Issue by tomchadwin** [sbenten/d3MapRenderer#14]
Page is on `http://127.0.0.1/`. Is `file:///` an option instead? To achieve this, the layers could no longer be loaded via AJAX - do they have to be?

**Comment by sbenten** [comment]
Yes, a web server is a prerequisite.

Json files can't be loaded via the file protocol, and d3 relies quite
heavily on Json and ajax.

It could be loaded from via file:// with the GeoJson data embedded in
Javascript but would not work with Topojson, and is not consistent with the
standard d3 practice.

**Comment by tomchadwin** [comment]
OK, I'll close this issue, as I'm not familiar enough with d3 to disagree. All I'd say is that increased prerequisites means increased barriers to adoption.
