### ISSUE TITLE
Symbology not being applied to polygons

### ISSUE THREAD

**Issue by smitty1788** [sbenten/d3MapRenderer#34]
When I create a map using QGIS2.18.3, the layer symbology is not being displayed correctly in the generated D3 map. It defaults every polygon to a shade of gray. This occurs in every single attempt. See image below for an example.

[![Homicides in 2015.png](https://s23.postimg.org/uqmr24rtn/Homicides_in_2015.png)](https://postimg.org/image/zcivahdcn/)

**Comment by sbenten** [comment]
Fixed on the 0.10 branch.  New version to be published as 0.10.2.
Dev version already fixed.
