### ISSUE TITLE
Cannot find the field value in the Viz tab

### ISSUE THREAD

**Issue by LPchong** [sbenten/d3MapRenderer#38]
I'm an amateur of QGIS. 

I am using the QGIS 2.18.14.  I would like to create a map which when people click / however an area on the map, a pop-up window will then show the bar charts (A map similar to [this][1])

I tried D3 Render Plugin and follow the guide [here][3].

However, I cannot select the field that I would like to visualize in the bar chart. Any advice what to do? 

[![enter image description here][4]][4]

  [1]: http://luminocity3d.org/WorldCity/#3/12.00/10.00
  [2]: https://gis.stackexchange.com/questions/227245/bar-column-charts-with-values
  [3]: http://maprenderer.org/d3/
  [4]: https://i.stack.imgur.com/8ySwl.png

**Comment by sbenten** [comment]
Hi

 

Can you confirm you have some numeric data types in your attribute table?

 

I think this got fixed on the master branch a long while ago. A release of QGis stopped using Integer data types in favour of Integer64.

 

So for now, you can either alter the offending line in the python code yourself, or download the master zip.

 

To do the change the code, alter the offending line in logic.py from:

            if f.typeName() == "Integer" or f.typeName() == "Real":

to:

            if f.typeName() == "Integer" or f.typeName() == "Real" or f.typeName() == "Integer64":

 

To download the master visit https://github.com/sbenten/d3MapRenderer/tree/master and click the “Clone or Downlod” link, and then select “Download Zip”. Unzip all files and folders over the previous version in your QGis plugin directory.

 

The downloaded version of d3MapRenderer resides in somewhere along the lines of “C:\Users\XXXXX\.qgis2\python\plugins\d3MapRenderer” where “XXXXX” is your logged in user’s home directory.

 

A authorised fix may take a few working days to get authorised, but will get there next week.

**Comment by LPchong** [comment]
It works well now. Thank you very much!
