### ISSUE TITLE
Website not starting

### ISSUE THREAD

**Issue by pcav** [sbenten/d3MapRenderer#41]
By default the plugin points to 127.0.0.1:8080, which in a standard setting does not respond. Any special reason to to run on localhost, as other web plugins do?
Thanks.

**Comment by sbenten** [comment]
This was taken from the default for the http-server npm package, but I'm
open to suggestions.

Default to http://localhost:8080 ? Or another port?

**Comment by pcav** [comment]
I suggest to follow the approach of qgis2web. In fact, merging your work with this plugin would be great @tomchadwin

**Comment by tomchadwin** [comment]
I did look at this back in early versions, but there were a lot of dissimilarities which could have made it problematic:

- the need for a local server (Leaflet/OpenLayers can work with local files), so the preview would have to be constructed very differently

- D3 didn't use EPSG CRSes, rather handing projections itself, and there seemed to be no easy way to select a D3 projection appropriate to the QGIS project

However, there are possibly ways that work could be done, if it was of interest.

**Comment by pcav** [comment]
OK, I see, thanks @tomchadwin for comments.
