### ISSUE TITLE
output path validation fails when a non ascii character is entered

### ISSUE THREAD

**Issue by volaya** [sbenten/d3MapRenderer#5]
this is the offending line. The str casting is causing the issue

https://github.com/sbenten/d3MapRenderer/blob/master/d3_Map.py#L388

**Comment by sbenten** [comment]
Hi, what operating system are you using?
Fixing the reported problem is quite straightforward, but I run into problems further down the line with the external call to the Node.js topojson package which converts the shapefile. 
On Windows it throws an exception as the DOS command line has its own encoding. Forcing this "cp850" encoding and replacing unknown characters then causes issues within topojson itself (it can't find the shapefile's dbf).
Not tried it on Linux yet.
